//
//  Copyright (C) 2012 Nufront Microsystems
//
//  File: FFmpegUtils.c
//  $Id: FFmpegUtils.c,v 1.1 2012/4/30 00:47:56 liuchao Exp $

/// @file FFmpegUtils.c
/// provide FFMPEG API to OMXCodec because ffmpeg decoder need some internal info

extern "C" {
#include "libavutil/opt.h"
#include "libavutil/avstring.h"
#include "libavformat/avformat.h"
#include "libavformat/internal.h"
#include "libavformat/httpauth.h"
#include "libavformat/url.h"
}
#define LOG_TAG "FFmpegUtils"
#include <unistd.h>
#include <media/stagefright/MediaDefs.h>
#include "FFmpegUtils.h"
#include "FFmpeg.h"


using namespace android;

#ifndef USE_NUAUDIO_DECODER
const MimeCodecTable FFmpegUtils::mime_codec_table[] = {
    {MEDIA_MIMETYPE_VIDEO_AVC, CODEC_ID_H264},
    {MEDIA_MIMETYPE_VIDEO_MPEG4, CODEC_ID_MPEG4},
    {MEDIA_MIMETYPE_VIDEO_MPEG4, CODEC_ID_MSMPEG4V3},
    {MEDIA_MIMETYPE_VIDEO_MPEG1, CODEC_ID_MPEG1VIDEO},
    {MEDIA_MIMETYPE_VIDEO_MPEG2, CODEC_ID_MPEG2VIDEO},
    {MEDIA_MIMETYPE_VIDEO_FLV1, CODEC_ID_FLV1},
    {MEDIA_MIMETYPE_VIDEO_VP6, CODEC_ID_VP6},
    {MEDIA_MIMETYPE_VIDEO_VP6F, CODEC_ID_VP6F},
    {MEDIA_MIMETYPE_VIDEO_VP6A, CODEC_ID_VP6A},
    {MEDIA_MIMETYPE_VIDEO_VC1, CODEC_ID_VC1},
    {MEDIA_MIMETYPE_VIDEO_VC1, CODEC_ID_WMV3},
    {MEDIA_MIMETYPE_VIDEO_H263, CODEC_ID_H263},
    {MEDIA_MIMETYPE_VIDEO_RV10,  CODEC_ID_RV10},
    {MEDIA_MIMETYPE_VIDEO_RV20,  CODEC_ID_RV20},
    {MEDIA_MIMETYPE_VIDEO_RV30,  CODEC_ID_RV30},
    {MEDIA_MIMETYPE_VIDEO_RV40,  CODEC_ID_RV40},
    {MEDIA_MIMETYPE_VIDEO_VP8, CODEC_ID_VP8},
    {MEDIA_MIMETYPE_VIDEO_VPX, CODEC_ID_VP8},
    {MEDIA_MIMETYPE_VIDEO_MJPEG, CODEC_ID_MJPEG},

    // various PCM "codecs"
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S16LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S16BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_U16LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_U16BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S8},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_U8},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_MULAW},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_ALAW},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S32LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S32BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_U32LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_U32BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S24LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S24BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_U24LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_U24BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S24DAUD},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_ZORK},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_S16LE_PLANAR},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_DVD},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_F32BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_F32LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_F64BE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_F64LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_BLURAY},
    {MEDIA_MIMETYPE_AUDIO_RAW, CODEC_ID_PCM_S16LE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_AAC},
    {MEDIA_MIMETYPE_AUDIO_MPEG, CODEC_ID_MP3},
    //{MEDIA_MIMETYPE_AUDIO_AMR_NB, CODEC_ID_AMR_NB},
    //{MEDIA_MIMETYPE_AUDIO_AMR_WB, CODEC_ID_AMR_WB},
    //{MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_PCM_LXF},

    //various ADPCM codecs
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_QT},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_WAV},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_DK3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_DK4},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_WS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_SMJPEG},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_MS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_4XM},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_XA},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_ADX},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_EA},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_G726},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_CT},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_SWF},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_YAMAHA},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_SBPRO_4},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_SBPRO_3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_SBPRO_2},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_THP},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_AMV},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_EA_R1},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_EA_R3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_EA_R2},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_EA_SEAD},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_EA_EACS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_EA_XAS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_EA_MAXIS_XA},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_IMA_ISS},
    //{MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ADPCM_G722},

    // AMR
    {MEDIA_MIMETYPE_AUDIO_AMR_NB, CODEC_ID_AMR_NB},
    {MEDIA_MIMETYPE_AUDIO_AMR_WB, CODEC_ID_AMR_WB},

    //RealAudio codecs
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_RA_144},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_RA_288},

    // various DPCM codecs
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ROQ_DPCM},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_INTERPLAY_DPCM},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_XAN_DPCM},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_SOL_DPCM},

    // audio codecs
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MP2},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MP3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_AAC},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_AC3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_DTS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_VORBIS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_DVAUDIO},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_WMAV1},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_WMAV2},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MACE3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MACE6},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_VMDAUDIO},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_SONIC},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_SONIC_LS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_FLAC},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MP3ADU},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MP3ON4},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_SHORTEN},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ALAC},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_WESTWOOD_SND1},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_GSM},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_QDM2},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_COOK},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_TRUESPEECH},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_TTA},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_SMACKAUDIO},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_QCELP},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_WAVPACK},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_DSICINAUDIO},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_IMC},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MUSEPACK7},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MLP},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_GSM_MS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ATRAC3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_VOXWARE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_APE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_NELLYMOSER},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MUSEPACK8},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_SPEEX},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_WMAVOICE},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_WMAPRO},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_WMALOSSLESS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ATRAC3P},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_EAC3},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_SIPR},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MP1},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_TWINVQ},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_TRUEHD},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_MP4ALS},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_ATRAC1},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_BINKAUDIO_RDFT},
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_BINKAUDIO_DCT},
    //{MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_AAC_LATM},
    //{MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_QDMC},

    //{MEDIA_MIMETYPE_AUDIO_AC3,   CODEC_ID_AC3},
    //{MEDIA_MIMETYPE_AUDIO_COOK,  CODEC_ID_COOK},
    //{MEDIA_MIMETYPE_AUDIO_RA_144, CODEC_ID_RA_144},
    //{MEDIA_MIMETYPE_AUDIO_RA_288, CODEC_ID_RA_288},
    //{MEDIA_MIMETYPE_AUDIO_ATRAC3,  CODEC_ID_ATRAC3},

    {NULL, CODEC_ID_NONE},
};
#else
// static vairable
const MimeCodecTable FFmpegUtils::mime_codec_table[] = {
    {MEDIA_MIMETYPE_VIDEO_AVC, CODEC_ID_H264},
    {MEDIA_MIMETYPE_VIDEO_MPEG4, CODEC_ID_MPEG4},
    {MEDIA_MIMETYPE_VIDEO_MPEG4, CODEC_ID_MSMPEG4V3},
    {MEDIA_MIMETYPE_VIDEO_MPEG1, CODEC_ID_MPEG1VIDEO},
    {MEDIA_MIMETYPE_VIDEO_MPEG2, CODEC_ID_MPEG2VIDEO},
    {MEDIA_MIMETYPE_VIDEO_FLV1, CODEC_ID_FLV1},
    {MEDIA_MIMETYPE_VIDEO_VP6, CODEC_ID_VP6},
    {MEDIA_MIMETYPE_VIDEO_VP6F, CODEC_ID_VP6F},
    {MEDIA_MIMETYPE_VIDEO_VP6A, CODEC_ID_VP6A},
    {MEDIA_MIMETYPE_VIDEO_VC1, CODEC_ID_VC1},
    {MEDIA_MIMETYPE_VIDEO_VC1, CODEC_ID_WMV3},
    {MEDIA_MIMETYPE_VIDEO_H263, CODEC_ID_H263},
    {MEDIA_MIMETYPE_VIDEO_RV10,  CODEC_ID_RV10},
    {MEDIA_MIMETYPE_VIDEO_RV20,  CODEC_ID_RV20},
    {MEDIA_MIMETYPE_VIDEO_RV30,  CODEC_ID_RV30},
    {MEDIA_MIMETYPE_VIDEO_RV40,  CODEC_ID_RV40},
    {MEDIA_MIMETYPE_VIDEO_VP8, CODEC_ID_VP8},
    {MEDIA_MIMETYPE_VIDEO_VPX, CODEC_ID_VP8},
    {MEDIA_MIMETYPE_VIDEO_MJPEG, CODEC_ID_MJPEG},

    // various PCM "codecs"
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S16LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S16BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_U16LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_U16BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S8},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_U8},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_MULAW},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_ALAW},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S32LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S32BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_U32LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_U32BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S24LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S24BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_U24LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_U24BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S24DAUD},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_ZORK},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_S16LE_PLANAR},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_DVD},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_F32BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_F32LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_F64BE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_F64LE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_BLURAY},
    {MEDIA_MIMETYPE_AUDIO_RAW, CODEC_ID_PCM_S16LE},
    //{MEDIA_MIMETYPE_AUDIO_MPEG, CODEC_ID_MP3},
    //{MEDIA_MIMETYPE_AUDIO_AMR_NB, CODEC_ID_AMR_NB},
    //{MEDIA_MIMETYPE_AUDIO_AMR_WB, CODEC_ID_AMR_WB},
    //{MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_PCM_LXF},

    //various ADPCM codecs
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_QT},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_WAV},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_DK3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_DK4},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_WS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_SMJPEG},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_MS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_4XM},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_XA},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_ADX},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_EA},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_G726},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_CT},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_SWF},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_YAMAHA},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_SBPRO_4},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_SBPRO_3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_SBPRO_2},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_THP},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_AMV},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_EA_R1},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_EA_R3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_EA_R2},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_EA_SEAD},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_EA_EACS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_EA_XAS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_EA_MAXIS_XA},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_IMA_ISS},
    //{MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ADPCM_G722},

    // AMR
    {MEDIA_MIMETYPE_AUDIO_AMR_NB, CODEC_ID_AMR_NB},
    {MEDIA_MIMETYPE_AUDIO_AMR_WB, CODEC_ID_AMR_WB},

    //RealAudio codecs
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_RA_144},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_RA_288},

    // various DPCM codecs
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ROQ_DPCM},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_INTERPLAY_DPCM},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_XAN_DPCM},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_SOL_DPCM},

    // audio codecs
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MP2},
#ifdef WITH_APU_CODEC
#ifdef WITH_MP3_APU_CODEC
    {MEDIA_MIMETYPE_AUDIO_MPEG, CODEC_ID_MP3},
#else
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MP3},
#endif
#ifdef WITH_AAC_APU_CODEC
    {MEDIA_MIMETYPE_AUDIO_AAC, CODEC_ID_AAC},
#else
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_AAC},
#endif
#else
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MP3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_AAC},
#endif
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_AC3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_DTS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_VORBIS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_DVAUDIO},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_WMAV1},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_WMAV2},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MACE3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MACE6},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_VMDAUDIO},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_SONIC},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_SONIC_LS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_FLAC},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MP3ADU},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MP3ON4},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_SHORTEN},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ALAC},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_WESTWOOD_SND1},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_GSM},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_QDM2},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_COOK},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_TRUESPEECH},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_TTA},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_SMACKAUDIO},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_QCELP},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_WAVPACK},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_DSICINAUDIO},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_IMC},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MUSEPACK7},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MLP},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_GSM_MS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ATRAC3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_VOXWARE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_APE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_NELLYMOSER},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MUSEPACK8},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_SPEEX},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_WMAVOICE},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_WMAPRO},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_WMALOSSLESS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ATRAC3P},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_EAC3},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_SIPR},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MP1},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_TWINVQ},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_TRUEHD},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_MP4ALS},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_ATRAC1},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_BINKAUDIO_RDFT},
    {MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_BINKAUDIO_DCT},
    //{MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_AAC_LATM},
    //{MEDIA_MIMETYPE_AUDIO_NUAUDIO, CODEC_ID_QDMC},

    //{MEDIA_MIMETYPE_AUDIO_AC3,   CODEC_ID_AC3},
    //{MEDIA_MIMETYPE_AUDIO_COOK,  CODEC_ID_COOK},
    //{MEDIA_MIMETYPE_AUDIO_RA_144, CODEC_ID_RA_144},
    //{MEDIA_MIMETYPE_AUDIO_RA_288, CODEC_ID_RA_288},
    //{MEDIA_MIMETYPE_AUDIO_ATRAC3,  CODEC_ID_ATRAC3},
    {NULL, CODEC_ID_NONE},
};
#endif



MimeCodecTable* FFmpegUtils::GetMimeCodecTable()
{
    return ((MimeCodecTable*) mime_codec_table);
}

int FFmpegUtils::GetCodecTableSize()
{
    MimeCodecTable* table = GetMimeCodecTable();

    if(table)
    {
        for(int i = 0x0; ; i++)
        {
            if(CODEC_ID_NONE == table[i].codec)
            {
                return i;
            }
        }
    }

    return 0x0;
}

void FFmpegUtils::SetAudioProfile(OMX_AUDIO_PARAM_NUAUDIOPROFILETYPE* profile, const char* mime)
{
    LCHLOGD1("mMIME = %s", mime);
    if (!strcasecmp(MEDIA_MIMETYPE_AUDIO_AAC, mime))
    {
        profile->codec_type = AVMEDIA_TYPE_AUDIO;
        profile->codec_id = CODEC_ID_AAC;
        profile->codec_tag = 1630826605; //mp4a
        profile->time_base_num = 0x0;
        profile->time_base_den = 0x1;
        profile->sample_fmt = AV_SAMPLE_FMT_S16;
        profile->sample_rate = 44100;
        profile->channels = 5;
        profile->frame_size = 1024;
        profile->frame_number = 1;
        profile->block_align = 0;
        profile->channel_layout = 0;
        profile->ticks_per_frame = 1;
        profile->audio_service_type = 0;
        profile->bits_per_coded_sample = 16;
        profile->bits_per_raw_sample = 0;
        profile->bit_rate = 8314;
        profile->flags = 0;
        profile->flags2 = 917760;
        profile->profile = -99;
    }
}

void FFmpegUtils::RegisterCodec(char* mime)
{
    static volatile int refs = 0;

    if ( refs++ == 0)
    {
        av_register_all();
        avcodec_register_all();
    }
}

void FFmpegUtils::DumpAudioProfile(OMX_AUDIO_PARAM_NUAUDIOPROFILETYPE* profile)
{
#if 0
    LCHLOGD2("codec_type = %d", profile->codec_type);
    LCHLOGD2("codec_id = %d", profile->codec_id);
    LCHLOGD2("codec_tag = %d", profile->codec_tag);
    LCHLOGD2("bit_rate = %d", profile->bit_rate);
    LCHLOGD2("flags = %d", profile->flags);
    LCHLOGD2("flags2 = %d", profile->flags2);
    LCHLOGD2("profile = %d", profile->profile );
    LCHLOGD2("time_base_num = %d", profile->time_base_num);
    LCHLOGD2("time_base_den = %d", profile->time_base_den);
    LCHLOGD2("extradata_size = %d", profile->extradata_size);
    int size = profile->extradata_size;
    LCHLOGD2("extradata = %p", profile->extradata);
    char* p = (char* ) profile->extradata;
    for(int i = 0x0; i < size; i++)
    {
        LCHLOGD2("extradata[%d] = 0x%x", i, p[i] & 0xFF);
    }

    LCHLOGD2("sample_fmt = %d", profile->sample_fmt);
    LCHLOGD2("sample_rate = %d", profile->sample_rate);
    LCHLOGD2("channels = %d", profile->channels);
    LCHLOGD2("frame_size = %d", profile->frame_size);

    LCHLOGD2("frame_number = %d", profile->frame_number);
    LCHLOGD2("block_align = %d", profile->block_align);
    LCHLOGD2("channel_layout = %d", profile->channel_layout);
    LCHLOGD2("ticks_per_frame = %d", profile->ticks_per_frame);
    LCHLOGD2("audio_service_type = %d", profile->audio_service_type);
    LCHLOGD2("bits_per_coded_sample = %d", profile->bits_per_coded_sample);
    LCHLOGD2("bits_per_raw_sample = %d", profile->bits_per_raw_sample);
#endif
}


