# video_decode
rm -rf ./hardware/nufront/media_115/

rm -rf ./hardware/nufront/media_2816/omx/video/src/openmax_il/video_decode/src/*
rm -f ./hardware/nufront/media_2816/omx/video/src/openmax_il/video_decode/Android.mk
cp ./out/target/product/nusmart2_smp/system/lib/libOMX.NU.Video.Decoder.so ./hardware/nufront/media_2816/omx/video/src/openmax_il/video_decode/src/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := src/libOMX.NU.Video.Decoder.so
include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_2816/omx/video/src/openmax_il/video_decode/Android.mk

# omx_core
rm -rf hardware/nufront/media_2816/omx/system/src/openmax_il/omx_core/src/*
rm -f hardware/nufront/media_2816/omx/system/src/openmax_il/omx_core/content.pkg
rm -f hardware/nufront/media_2816/omx/system/src/openmax_il/omx_core/Makefile
cp ./out/target/product/nusmart2_smp/system/lib/libOMX_Core.so ./hardware/nufront/media_2816/omx/system/src/openmax_il/omx_core/src/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libOMX_Core.so
include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_2816/omx/system/src/openmax_il/omx_core/src/Android.mk

# libstagefrighthw
rm -rf ./hardware/nufront/media_2816/libstagefrighthw/*.cpp
rm -f ./hardware/nufront/media_2816/libstagefrighthw/Android.mk
cp ./out/target/product/nusmart2_smp/system/lib/libstagefrighthw.so ./hardware/nufront/media_2816/libstagefrighthw/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libstagefrighthw.so
include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_2816/libstagefrighthw/Android.mk

#vpu

if [[ -d ./hardware/nufront/media_2816/vpu/decode ]]; then
    cd ./hardware/nufront/media_2816/vpu/decode
    for f in `find . -not -name "*.h"`; do
        if [[ -f $f ]]; then
            rm -fr $f
        else
            echo $f 'directory in ./hardware/nufront/media_2816/vpu/decode will not be deleted, this is a correct operation'
        fi
    done;
    cd ../../../../../
else
        echo './hardware/nufront/media_2816/vpu/decode does not exist'
fi
cp ./out/target/product/nusmart2_smp/system/lib/libdec8190vp6.so  ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdecx170m2.so   ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdecx170p.so    ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdecx170v.so    ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdecx170h.so    ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdecx170m.so    ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdecx170rv.so   ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdwlx170.so     ./hardware/nufront/media_2816/vpu/decode
cp ./out/target/product/nusmart2_smp/system/lib/libdecx170jpeg.so ./hardware/nufront/media_2816/vpu/decode

echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED #

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libdec8190vp6.so  libdecx170m2.so  libdecx170p.so \
                       libdecx170v.so    libdecx170h.so   libdecx170m.so \
					   libdecx170rv.so   libdwlx170.so    libdecx170jpeg.so

include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_2816/vpu/decode/Android.mk
