export GRAPHICS_TARGET_DEVICE=nusmart3_pad

# customize mali
cd ./hardware/nufront/mali
mv ./src/ump/include ./ump_include
rm -rf ./testbench/ ./src/* ./presets/ ./build_system/
mkdir ./src/ump
mv ./ump_include ./src/ump/include
rm -f Doxy* Makefile* *.c version_info.mak topleveldir Android.mk*
cd ../../../
cp ./out/target/product/${GRAPHICS_TARGET_DEVICE}/system/lib/libMali.so ./hardware/nufront/mali/src/
cp ./out/target/product/${GRAPHICS_TARGET_DEVICE}/system/lib/libUMP.so ./hardware/nufront/mali/src/
cp ./out/target/product/${GRAPHICS_TARGET_DEVICE}/system/lib/egl/libEGL_mali.so ./hardware/nufront/mali/src/
cp ./out/target/product/${GRAPHICS_TARGET_DEVICE}/system/lib/egl/libGLESv1_CM_mali.so ./hardware/nufront/mali/src/
cp ./out/target/product/${GRAPHICS_TARGET_DEVICE}/system/lib/egl/libGLESv2_mali.so ./hardware/nufront/mali/src/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2012 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH:= \$(call my-dir)
ifneq (\$(TARGET_CPU_SMP),true)
@echo \"You must choose TARGET_CPU_SMP=true\n\"
endif

# libMali
include \$(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libMali
LOCAL_PREBUILT_LIBS := src/libMali.so

include \$(BUILD_MULTI_PREBUILT)

# libUMP
include \$(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libUMP
LOCAL_PREBUILT_LIBS := src/libUMP.so

include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/mali/Android.mk

sed -i '/\$(call inherit-product, frameworks\/base\/build\/tablet-dalvik-heap.mk)/i\
PRODUCT_COPY_FILES += \\\n\thardware\/nufront\/mali\/src\/libGLESv1_CM_mali.so:system\/lib\/egl\/libGLESv1_CM_mali.so \\\n\thardware\/nufront\/mali\/src\/libGLESv2_mali.so:system\/lib\/egl\/libGLESv2_mali.so \\\n\thardware\/nufront\/mali\/src\/libEGL_mali.so:system\/lib\/egl\/libEGL_mali.so\n' ./device/nufront/${GRAPHICS_TARGET_DEVICE}/device.mk

# customize gal
cd ./hardware/nufront/gal
rm -rf ./arch ./os Android.mk* *.c *.h makefile.linux
cd ../../../
cp ./out/target/product/${GRAPHICS_TARGET_DEVICE}/system/lib/libGAL.so ./hardware/nufront/gal/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2012 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH:= \$(call my-dir)

#
# libGAL
#
include \$(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libGAL
LOCAL_PREBUILT_LIBS := libGAL.so

include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/gal/Android.mk
