# video_decode
rm -rf ./hardware/nufront/media_2816/

rm -rf ./hardware/nufront/media_115/apu
rm -rf ./hardware/nufront/media_115/omx/audio/src/openmax_il/nuapu_codec/

rm -rf ./hardware/nufront/media_115/omx/video/src/openmax_il/video_decode/src/*
rm -f ./hardware/nufront/media_115/omx/video/src/openmax_il/video_decode/Android.mk
cp ./out/target/product/nusmart3_pad/system/lib/libOMX.NU.Video.Decoder.so ./hardware/nufront/media_115/omx/video/src/openmax_il/video_decode/src/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := src/libOMX.NU.Video.Decoder.so
include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_115/omx/video/src/openmax_il/video_decode/Android.mk

# omx_core
rm -rf hardware/nufront/media_115/omx/system/src/openmax_il/omx_core/src/*
rm -f hardware/nufront/media_115/omx/system/src/openmax_il/omx_core/content.pkg
rm -f hardware/nufront/media_115/omx/system/src/openmax_il/omx_core/Makefile
cp ./out/target/product/nusmart3_pad/system/lib/libOMX_Core.so ./hardware/nufront/media_115/omx/system/src/openmax_il/omx_core/src/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libOMX_Core.so
include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_115/omx/system/src/openmax_il/omx_core/src/Android.mk

# libstagefrighthw
rm -rf ./hardware/nufront/media_115/libstagefrighthw/*.cpp
rm -f ./hardware/nufront/media_115/libstagefrighthw/Android.mk
cp ./out/target/product/nusmart3_pad/system/lib/libstagefrighthw.so ./hardware/nufront/media_115/libstagefrighthw/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libstagefrighthw.so
include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_115/libstagefrighthw/Android.mk

#vpu decode

if [[ -d ./hardware/nufront/media_115/vpu/decode ]]; then
    cd ./hardware/nufront/media_115/vpu/decode
    for f in `find . -not -name "*.h"`; do
        if [[ -f $f ]]; then
            rm -fr $f
        else
            echo $f 'directory in ./hardware/nufront/media_115/vpu/decode will not be deleted, this is a correct operation'
        fi
    done;
    cd ../../../../../
else
        echo './hardware/nufront/media_115/vpu/decode does not exist'
fi

cp ./out/target/product/nusmart3_pad/system/lib/libdec8190vp6.so  ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdecx170m2.so   ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdecx170a.so    ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdecx170v.so    ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdecx170h.so    ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdecx170m.so    ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdecx170rv.so   ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdwlx170.so     ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdec8190vp8.so  ./hardware/nufront/media_115/vpu/decode
cp ./out/target/product/nusmart3_pad/system/lib/libdecx170jpeg.so ./hardware/nufront/media_115/vpu/decode

echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED #

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libdec8190vp6.so  libdec8190vp8.so  libdecx170a.so  \
                       libdecx170h.so  libdecx170jpeg.so  libdecx170m2.so  \
                       libdecx170m.so  libdecx170rv.so  libdecx170v.so libdwlx170.so

include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_115/vpu/decode/Android.mk

#vpu encode

if [[ -d ./hardware/nufront/media_115/vpu/encode/ ]]; then
    cd ./hardware/nufront/media_115/vpu/encode/
    for f in `find . -not -name "*.h"`; do
        if [[ -f $f ]]; then
            rm -fr $f
        else
            echo $f 'directory in ./hardware/nufront/media_115/vpu/encode/ will not be deleted, this is a correct operation'
        fi
    done;
    cd ../../../../../
else
        echo './hardware/nufront/media_115/vpu/encode/ does not exist'
fi

cp ./out/target/product/nusmart3_pad/system/lib/libh1enc.so  ./hardware/nufront/media_115/vpu/encode/
echo "#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED #

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libh1enc.so

include \$(BUILD_MULTI_PREBUILT)" > ./hardware/nufront/media_115/vpu/encode/Android.mk
