#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2012 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH:= $(call my-dir)
ifneq ($(TARGET_CPU_SMP),true)
@echo "You must choose TARGET_CPU_SMP=true\n"
endif

# libMali
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libMali
LOCAL_PREBUILT_LIBS := src/libMali.so

include $(BUILD_MULTI_PREBUILT)

# libUMP
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libUMP
LOCAL_PREBUILT_LIBS := src/libUMP.so

include $(BUILD_MULTI_PREBUILT)
